test: comment to identify the mistake

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,29 +9,29 @@ on:
       - prod
 
 jobs:
-  .build:
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v3
+#   build:
+#     runs-on: ubuntu-22.04
+#     steps:
+#       - uses: actions/checkout@v3
 
-      - name: Set up JDK 21
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'temurin'
-          java-version: '21'
+#       - name: Set up JDK 21
+#         uses: actions/setup-java@v3
+#         with:
+#           distribution: 'temurin'
+#           java-version: '21'
 
-      - name: Grant execute permission for gradlew
-        run: chmod +x ./gradlew
+#       - name: Grant execute permission for gradlew
+#         run: chmod +x ./gradlew
 
-      - name: Build with Gradle
-        run: ./gradlew build -x test
+#       - name: Build with Gradle
+#         run: ./gradlew build -x test
 
-      - name: Archive production artifacts
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: production-artifacts
-          path: build/libs/*.jar
+#       - name: Archive production artifacts
+#         if: success() || failure()
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: production-artifacts
+#           path: build/libs/*.jar
   test:
     runs-on: ubuntu-22.04
     # needs: build
